### ISSUE TITLE
Nastavení AWS

### ISSUE THREAD

**Issue by JakubTrousil** [Edunacoadmin/Edunaco#21]
Budou doplněny jednotlivé kroky, až bude issue k realizaci, tak bude přeřazeno na vlastníka.

**Comment by JakubTrousil** [comment]
https://us-east-1.console.aws.amazon.com/organizations/v2/home/policies/service-control-policy

### Tři pravidla:

![image](https://user-images.githubusercontent.com/18667010/221436645-b659638b-3f2c-463d-9e00-18ba7e2168a6.png)

Amplify
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "Statement1",
      "Effect": "Allow",
      "Action": [
        "amplify:*",
        "amplifybackend:*"
      ],
      "Resource": "*"
    }
  ]
}
```
ListRegions
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "Statement1",
      "Effect": "Allow",
      "Action": [
        "account:ListRegions"
      ],
      "Resource": "*"
    }
  ]
}
```
Route53
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "route53:*",
        "route53domains:*"
      ],
      "Resource": "*"
    }
  ]
}
```

### Práva vlastníka organizace zde:
https://us-east-1.console.aws.amazon.com/organizations/v2/home/accounts a prokliknout se do jeho profilu. A zde přes attach přidat FullAWSAccess
![image](https://user-images.githubusercontent.com/18667010/221436854-64f6c5db-68ea-4934-8e85-0b504cf16b0a.png)

### Práva celé skupiny
https://us-east-1.console.aws.amazon.com/organizations/v2/home/accounts - prokliknout se na Root a tam přes Detach odebrat FullAWSAccess z celé skupiny a přidat tři vytvořená pravidla.

**Comment by Edunacoadmin** [comment]
Done
